[package]
name = "doujin"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
futures = "0.3.31"
glob = "0.3.2"
indicatif = "0.17.11"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
